<?xml version="1.0"?>
<robot name="parallel_car" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- include xacro files -->
    <xacro:include filename="$(find parallel_car)/urdf/parallel_car.gazebo.xacro"/>
    <xacro:include filename="$(find parallel_car)/urdf/parallel_car.transmission.xacro"/>
    
    <!--xacro properties-->
    <xacro:property name="car_mass" value="20.0"/>
    <xacro:property name="wx_mass" value="5.0"/>
    <xacro:property name="PI" value="3.1415926536"/>
    <xacro:property name="bar_length" value="1.0"/>
    <xacro:property name="bar_width" value="0.05"/>
    <xacro:property name="little_width" value="0.001"/>
    <xacro:property name="wx_length" value="0.55"/>


    <!-- links -->
    <link name="car_link"><!--from origin to top-->
        <visual>
            <geometry>
	            <mesh filename="package://parallel_car/meshes/car.STL" />
     	    </geometry>
            <material name="ForestGreen">
                <color rgba="0.15 0.5 0.15 0.5"/>
            </material>
            <origin rpy="${PI/2.0} 0 ${PI/2.0}" xyz="0 0 0.23"/>
        </visual>
        <collision>
            <geometry>
	            <mesh filename="package://parallel_car/meshes/car.STL" />
     	    </geometry>
            <origin rpy="${PI/2.0} 0 ${PI/2.0}" xyz="0 0 0.23"/>
        </collision>
        <inertial>
            <mass value="${car_mass}"/>
            <inertia ixx="${car_mass}" ixy="0.0" ixz="0.0" iyy="${car_mass}" iyz="0.0" izz="${car_mass}" />
        </inertial>
    </link>

    <link name="barX_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${bar_length} ${bar_width} ${bar_width}"/>
            </geometry>
            <material name = "Blue">
                <color rgba = "0.0 0.0 1.0 0.5"/>
            </material>
        </visual>
    </link>

    <link name="barY_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${bar_width} ${bar_length} ${bar_width}"/>
            </geometry>
            <material name = "Crimson">
                <color rgba="0.8 0.1 0.25 0.5"/>
            </material>
        </visual>
    </link>

    <link name="barZ_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${bar_width} ${bar_width} ${bar_length}"/>
            </geometry>
            <material name="Yellow">
                <color rgba="1.0 1.0 0.0 0.5"/>
            </material>
        </visual>
    </link>

    <link name="littleX_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${little_width} ${little_width} ${little_width}"/>
            </geometry>
            <material name="Chocolate">
                <color rgba="0.8 0.5 0.125 0.5"/>
            </material>
        </visual>
    </link>

    <link name="littleY_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${little_width} ${little_width} ${little_width}"/>
            </geometry>
            <material name="DarkGreen">
                <color rgba="0.0 0.5 0.0 0.5"/>
            </material>
        </visual>
    </link>

    <link name="littleZ_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${little_width} ${little_width} ${little_width}"/>
            </geometry>
            <material name="Red">
                <color rgba="1.0 0.0 0.0 0.5"/>
            </material>
        </visual>
    </link>

    <link name="wx_link">
        <inertial>
            <origin xyz="0.0 0.0 ${wx_length/2.0}" rpy="0.0 0.0 0.0"/>
            <mass value="${wx_mass}"/>
            <inertia ixx="${wx_mass}" ixy="0.0" ixz="0.0" iyy="${wx_mass}" iyz="0.0" izz="${wx_mass}"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 ${wx_length}" rpy="0.0 ${PI} 0.0"/>
            <geometry>
                <mesh filename="package://parallel_car/meshes/MZ.STL" />
            </geometry>
            <material name="White">
                <color rgba="1.0 1.0 1.0 0.5"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${wx_length}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://parallel_car/meshes/MZ.STL" />
            </geometry>
        </collision>
    </link>


    <!-- joints -->

    <joint name="car_to_barX" type="prismatic">
        <origin xyz="0.0 0.0 0.18" rpy="0.0 0.0 0.0"/>
        <parent link="car_link"/>
        <child link="barX_link"/>
        <axis xyz="1.0 0.0 0.0"/>
        <limit lower="-0.5" upper="0.5" effort="5.0" velocity="0.5"/>
    </joint>

    <joint name="barX_to_barY" type="prismatic">
        <origin xyz="0.0 0.0 ${bar_width}" rpy="0.0 0.0 0.0"/>
        <parent link="barX_link"/>
        <child link="barY_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="-0.5" upper="0.5" effort="5.0" velocity="0.5"/>
    </joint>

    <joint name="barY_to_barZ" type="prismatic">
        <origin xyz="0.0 0.0 ${(bar_length+bar_width)/2.0}" rpy="0.0 0.0 0.0"/>
        <parent link="barY_link"/>
        <child link="barZ_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="-0.5" upper="0.5" effort="5.0" velocity="0.5"/>
    </joint>

    <joint name="barZ_to_littleX" type="revolute">
        <origin xyz="0.0 0.0 ${bar_length/2.0}" rpy="0.0 0.0 0.0"/>
        <parent link="barZ_link"/>
        <child link="littleX_link"/>
        <axis xyz="1.0 0.0 0.0"/>
        <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="5.0" velocity="0.5"/>
    </joint>

    <joint name="littleX_to_littleY" type="revolute">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="littleX_link"/>
        <child link="littleY_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="5.0" velocity="0.5"/>
    </joint>

    <joint name="littleY_to_littleZ" type="revolute">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="littleY_link"/>
        <child link="littleZ_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="5.0" velocity="0.5"/>
    </joint>

    <joint name="littleZ_to_wx" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="littleZ_link"/>
        <child link="wx_link"/>
    </joint>


</robot>