<?xml version="1.0"?>
<robot name="parallel_car" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--xacro properties-->
    <xacro:property name="car_mass" value="20.0"/>
    <xacro:property name="PI" value="3.1415926536"/>
    <xacro:property name="bar_length" value="1.0"/>
    <xacro:property name="bar_width" value="0.05"/>


    <!-- links -->
    <link name="car_link"><!--from origin to top-->
        <visual>
            <geometry>
	            <mesh filename="package://parallel_car/meshes/car.STL" />
     	    </geometry>
            <material name="ForestGreen">
                <color rgba="0.15 0.5 0.15 0.5"/>
            </material>
            <origin rpy="${PI/2.0} 0 ${PI/2.0}" xyz="0 0 0.23"/>
        </visual>
        <collision>
            <geometry>
	            <mesh filename="package://parallel_car/meshes/car.STL" />
     	    </geometry>
            <origin rpy="${PI/2.0} 0 ${PI/2.0}" xyz="0 0 0.23"/>
        </collision>
        <inertial>
            <mass value="${car_mass}"/>
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>

    <link name="barX_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${bar_length} ${bar_width} ${bar_width}"/>
            </geometry>
            <material name = "Blue">
                <color rgba = "0.0 0.0 1.0 0.5"/>
            </material>
        </visual>
    </link>

    <link name="barY_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${bar_length} ${bar_width} ${bar_width}"/>
            </geometry>
            <material name = "Crimson">
                <color rgba="0.8 0.1 0.25 0.5"/>
            </material>
        </visual>
    </link>

    <link name="barZ_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.01"/>
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${bar_width} ${bar_width} ${bar_length}"/>
            </geometry>
            <material name="Yellow">
                <color rgba="1.0 1.0 0.0 0.5"/>
            </material>
        </visual>
    </link>


    <!-- joints -->

    <joint name="car_to_barX" type="prismatic">
        <origin xyz="0.0 0.0 0.18" rpy="0.0 0.0 0.0"/>
        <parent link="car_link"/>
        <child link="barX_link"/>
        <axis xyz="1.0 0.0 0.0"/>
        <limit lower="-0.5" upper="0.5" effort="0.5" velocity="0.5"/>
    </joint>

    <joint name="barX_to_barY" type="prismatic">
        <origin xyz="0.0 0.0 ${bar_width}" rpy="0.0 0.0 ${PI/2.0}"/>
        <parent link="barX_link"/>
        <child link="barY_link"/>
        <axis xyz="1.0 0.0 0.0"/>
        <limit lower="-0.5" upper="0.5" effort="0.5" velocity="0.5"/>
    </joint>

    <joint name="barY_to_barZ" type="prismatic">
        <origin xyz="0.0 0.0 ${(bar_length+bar_width)/2.0}" rpy="0.0 0.0 0.0"/>
        <parent link="barY_link"/>
        <child link="barZ_link"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="-0.5" upper="0.5" effort="0.5" velocity="0.5"/>
    </joint>


</robot>