parallel_car:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50  
    
    mech_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - car_to_barX
        - barX_to_barY
        - barY_to_barZ
        - barZ_to_littleX
        - littleX_to_littleY
        - littleY_to_littleZ
      constraints:
          goal_time: 0.6
          stopped_velocity_tolerance: 0.01
          joint1: {trajectory: 0.01, goal: 0.01}
          joint2: {trajectory: 0.01, goal: 0.01}
      stop_trajectory_duration: 0.0
      state_publish_rate:  50
      action_monitor_rate: 20