parallel_car:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50  
    
    mech_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - car_to_barX
        - barX_to_barY
        - barY_to_barZ
        - barZ_to_littleX
        - littleX_to_littleY
        - littleY_to_littleZ
        - addon_Tilt_to_wx
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.01
        car_to_barX: {trajectory: 0.01, goal: 0.01}
        barX_to_barY: {trajectory: 0.01, goal: 0.01}
        barY_to_barZ: {trajectory: 0.01, goal: 0.01}
        barZ_to_littleX: {trajectory: 0.01, goal: 0.01}
        littleX_to_littleY: {trajectory: 0.01, goal: 0.01}
        littleY_to_littleZ: {trajectory: 0.01, goal: 0.01}
        addon_Tilt_to_wx: {trajectory: 0.01, goal: 0.01}
      stop_trajectory_duration: 0.0
      state_publish_rate:  50
      action_monitor_rate: 20

    support_and_mech_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - world_to_supportX
        - supportX_to_supportY
        - supportY_to_car
        - car_to_barX
        - barX_to_barY
        - barY_to_barZ
        - barZ_to_littleX
        - littleX_to_littleY
        - littleY_to_littleZ
        - addon_Tilt_to_wx
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.01
        world_to_supportX: {trajectory: 0.01, goal: 0.01}
        supportX_to_supportY: {trajectory: 0.01, goal: 0.01}
        supportY_to_car: {trajectory: 0.01, goal: 0.01}
        car_to_barX: {trajectory: 0.01, goal: 0.01}
        barX_to_barY: {trajectory: 0.01, goal: 0.01}
        barY_to_barZ: {trajectory: 0.01, goal: 0.01}
        barZ_to_littleX: {trajectory: 0.01, goal: 0.01}
        littleX_to_littleY: {trajectory: 0.01, goal: 0.01}
        littleY_to_littleZ: {trajectory: 0.01, goal: 0.01}
        addon_Tilt_to_wx: {trajectory: 0.01, goal: 0.01}
      stop_trajectory_duration: 0.0
      state_publish_rate:  50
      action_monitor_rate: 20